# Generated by Django 5.1.4 on 2025-03-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('attendant', 'Lab Attendant')], default='attendant', max_length=100),
        ),
    ]
