# Generated by Django 5.1.4 on 2025-03-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('attendant', 'Lab Attendant')], default='attendant', max_length=100),
        ),
    ]
