# Generated by Django 5.1.6 on 2025-02-18 22:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chemicals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField(help_text='in gram(g) or liter(L)')),
                ('description', models.TextField()),
                ('vendor', models.CharField(max_length=100)),
                ('hazard_information', models.TextField()),
                ('molecular_formula', models.CharField(max_length=100)),
                ('reactivity_group', models.CharField(choices=[('Alkali', 'Alkali'), ('Alkaline Earth', 'Alkaline Earth'), ('Transition Metal', 'Transition Metal'), ('Lanthanide', 'Lanthanide'), ('Actinide', 'Actinide'), ('Metal', 'Metal'), ('Nonmetal', 'Nonmetal'), ('Halogen', 'Halogen'), ('Noble Gas', 'Noble Gas'), ('Other', 'Other')], max_length=255)),
                ('chemical_type', models.CharField(choices=[('Organic', 'Organic'), ('Inorganic', 'Inorganic'), ('Both', 'Both')], max_length=100)),
                ('chemical_state', models.CharField(choices=[('Solid', 'Solid'), ('Liquid', 'Liquid'), ('Gas', 'Gas'), ('Plasma', 'Plasma'), ('Other', 'Other')], max_length=100)),
                ('expires', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chemical', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemicals', to='inventory.locations')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chemical_state'], name='inventory_c_chemica_f10e71_idx'), models.Index(fields=['chemical_type'], name='inventory_c_chemica_b11009_idx'), models.Index(fields=['-created_at'], name='inventory_c_created_bd151b_idx'), models.Index(fields=['expires'], name='inventory_c_expires_98f309_idx')],
            },
        ),
    ]
