# Generated by Django 5.1.7 on 2025-04-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_chemicalactivity_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalactivity',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('removed', 'Removed'), ('used', 'Used'), ('restocked', 'Restocked')], max_length=20),
        ),
    ]
